import './bootstrap';
import './interactions';
import Alpine from 'alpinejs';
import {
    Activity,
    AlertCircle,
    Bell,
    BookOpen,
    Briefcase,
    Building,
    CalendarDays,
    ChartColumn,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Circle,
    CircleCheck,
    ClipboardList,
    Ellipsis,
    FileChartColumn,
    FolderKanban,
    Home,
    KeyRound,
    Landmark,
    Languages,
    LayoutDashboard,
    LogOut,
    Menu,
    MessageCircle,
    Package,
    PanelLeft,
    Phone,
    Plus,
    Receipt,
    Search,
    Settings,
    TrendingUp,
    Upload,
    User,
    UserCog,
    Users,
    Wallet,
    Wrench,
    X,
    createIcons,
} from 'lucide';

window.Alpine = Alpine;

Alpine.start();
// Every name mapped in components/notify/icon.blade.php must be registered here.
createIcons({
    icons: {
        Activity,
        AlertCircle,
        Bell,
        BookOpen,
        Briefcase,
        Building,
        CalendarDays,
        ChartColumn,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        Circle,
        CircleCheck,
        ClipboardList,
        Ellipsis,
        FileChartColumn,
        FolderKanban,
        Home,
        KeyRound,
        Landmark,
        Languages,
        LayoutDashboard,
        LogOut,
        Menu,
        MessageCircle,
        Package,
        PanelLeft,
        Phone,
        Plus,
        Receipt,
        Search,
        Settings,
        TrendingUp,
        Upload,
        User,
        UserCog,
        Users,
        Wallet,
        Wrench,
        X,
    },
});
